spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:auth;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

uri:
  scheme: http
  host: localhost
  port: 8080

app.security.jwt:
  tokenExpirationSec: ${jwt.token}
  refreshExpirationSec: ${jwt.refresh}
  tokenIssuer: ${jwt.issuer}
  base64TokenSigningKey: ${jwt.base64}

toss:
  payments:
    secretKey: ${toss.secret}
    url: ${toss.url}