package org.collaborators.paymentslab.payment.infrastructure.tosspayments.exception

import org.collaborator.paymentlab.common.error.ErrorCode
import org.collaborator.paymentlab.common.error.ServiceException

class AlreadyDonePaymentOrderException: ServiceException(ErrorCode.ALREADY_DONE_PAYMENT_ORDER)