package org.collaborators.paymentslab.payment.infrastructure.tosspayments.exception

import org.collaborator.paymentlab.common.error.ErrorCode
import org.collaborator.paymentlab.common.error.ServiceException

class AlreadyAbortedPaymentOrderException: ServiceException(ErrorCode.ALREADY_ABORTED_PAYMENT_ORDER)