package org.collaborators.paymentslab.payment.infrastructure.tosspayments.exception

import org.collaborator.paymentlab.common.error.ErrorCode
import org.collaborator.paymentlab.common.error.ServiceException

class AlreadyCanceledPaymentOrderException: ServiceException(ErrorCode.ALREADY_CANCELED_PAYMENT_ORDER)