package org.collaborators.paymentslab.payment.infrastructure.tosspayments.exception

import org.collaborator.paymentlab.common.error.ErrorCode
import org.collaborator.paymentlab.common.error.ServiceException

class InvalidPaymentOrderStatusException: ServiceException(ErrorCode.INVALID_PAYMENT_ORDER_STATUS)